name: Validate Renovate Config

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["**"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  renovate-config-validation:
    name: Run Renovate Config Validation
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout Repo
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false

      - name: Install Tools & Dependencies
        uses: withstudiocms/automations/.github/actions/install@885437ef4376e64fc295161092b8a165bc5efd39 # main

      - name: Run Renovate Config Validation
        run: pnpm dlx --package renovate -- renovate-config-validator default.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}